services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5111:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stockPriceCheckerDB
